### ISSUE TITLE
Netsplit behavior

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#11]
I can use some clarification about the behavior of miniirc in the event of a netsplit. I had multiple bots running on a IRC server, and one of them didn't reconnect to the server after a netsplit. The others did reconnect. I waited long enough for it. Can the behavior of miniirc in dealing with netsplits be clarified? Can I expect and trust it to reconnect by itself? Also, what happens if I try to use the `msg` and/or `quote` methods while it's not connected to the server? I don't have debug logs as collecting them would be too noisy except in a test setting. Thanks.

**Comment by luk3yx** [comment]
It doesn't periodically ping the server at the moment (it probably should).

**Comment by luk3yx** [comment]
The [timeout] branch should fix this after more testing.

[timeout]: https://github.com/luk3yx/miniirc/tree/timeout

**Comment by impredicative** [comment]
I haven't tested it but that looks good to me at a cursory glance.

Also, what currently happens if I try to use the msg and/or quote methods while it's not connected to the server?

**Comment by luk3yx** [comment]
It will temporarily store the command (unless you use `force=True`) until you are connected (it will probably execute them before the first `JOIN`, however).

**Comment by impredicative** [comment]
OK. On my part I will try to better track when the client leaves a channel, so I don't send messages to a channel if the client has left the channel due to a disconnection, etc.

**Comment by impredicative** [comment]
I will give 1.2.0 a try. Thanks.

**Comment by luk3yx** [comment]
I ran into a strange bug on Python 3.5, if 1.2.0 doesn't work try 1.2.2.

**Comment by impredicative** [comment]
You should be able to delete specific versions at https://pypi.org/manage/project/miniirc/releases/

I will revert to 1.1.4 for now.

**Comment by luk3yx** [comment]
The issue has (hopefully) been fixed, I don't think it affected Python 3.7.

**Comment by impredicative** [comment]
Pinging the server and reconnecting is good, but for particular bots, I'd still like to ensure that the connection to the server is active before I send messages to the channel and log them as having been sent. I had an incident yesterday where the RSS bot ate a feed and didn't actually post it to the channel. I acknowledge that IRC itself may not have a means of ensuring reliable transmission of messages. What would be a good approximate workaround for this?

In the simplest case, I can check the last receive PONG time. If it's not within the last `ping_interval` seconds, I will wait till it is. Obviously this is not reliable enough.

I can maybe send a PING and wait for a PONG just before I send a batch of messages. I can then also send a PING and wait for a PONG after the batch is sent. If both PONGs work within say 3 seconds of their respective PINGs, then I call it a success, otherwise a failure. To this end, can miniirc provide a helper method that helps me confirm connectivity in this way, or in any better way? I would call it as `irc.is_connected()` and it would return True or False. If it had already happened to receive a PONG in the last 3 seconds, then it doesn't need to send a PING.

What may be even better is a context manager that ensures the connection: `with irc.ensure_connection():`, I send my messages. If the PONG fails in this period, a known exception gets raised by the context manager, and I can then consider the batch a failure.

**Comment by luk3yx** [comment]
`irc.connected` gets set to `True` while connected, however it gets set before the initial `JOIN` is sent. I like the idea of `irc.ensure_connection()`, I'll probably create it (or something similar) in the next feature release.

**Comment by luk3yx** [comment]
miniirc 1.2.4 now clears the `irc.quote()` buffer after sending `JOIN`, messages sent while disconnected should be properly handled now (however on channels with `+m` set you'd probably have to wait until ChanServ sets `+v`).

**Comment by impredicative** [comment]
Thanks. I will update my bots to 1.2.4.
