### ISSUE TITLE
Readme on PyPI for 1.2.4 is misformatted

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#14]
The readme on pypi for 1.2.4 is [broken](https://pypi.org/project/miniirc/1.2.4/). Was a specific Github-flavored markdown feature used that pypi wouldn't support? It was [working](https://pypi.org/project/miniirc/1.2.3/) for 1.2.3.

**Comment by luk3yx** [comment]
I released 1.2.4 on a different machine that I don't think has the latest `wheel` package, I'll fix it later.

**Comment by luk3yx** [comment]
Fixed, thanks for reporting the issue.
