### ISSUE TITLE
Consider context manager: irc.ensure_connection

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#15]
Per our prior discussion, this issue exists to think about and possibly implement a context manager which offers a better than normal reliability of an active connection. It is intended to be used for short periods of time such as when sending a batch of messages or other commands. It could work by internally using PING and expecting PONG at a far higher rate than usual rate of `ping_interval`. The user's code can look something like this:

```python
while True:
    with irc.ensure_connection(period=3, timeout=2):
        for msg in messages:
            irc.msg(channel, msg)
            time.sleep(2)
        for cmd in commands:
            irc.quote(*cmd)
            time.sleep(2)
    except irc.ConnectionError as exc:
        logging.exception('A connection error was encountered while processing the batch. It will be retried.')
        time.sleep(5)
    else:
        break
```

If the PING/PONG strategy is used, if the PONG is not received within say `timeout` seconds (default 2) of the PING, `irc.ConnectionError` can be raised. A PING could be sent every `period` seconds (default 3), and also definitely when releasing the context! I don't know IRC well enough, so this is my naive strategy.

I especially haven't given enough thought to the blocking vs non-blocking nature of this context manager, and so I'm hesitant to request it at all. **Often the commands that are run are very time-sensitive, and it may not make sense to wait much to run them.**

**Comment by luk3yx** [comment]
If this is implemented (and I understand it correctly), then:
 - `irc.quote()` inside `irc.ensure_connection` will raise an error if miniirc is disconnected, and the ping interval will be temporarily reduced.
 - `irc.quote()` outside `irc.ensure_connection` will work as per normal, and if miniirc is not connected to IRC, will not be sent until it is.

*Commands such as `irc.msg()` call `irc.quote()` internally and would work with `irc.ensure_connection()`.*

Is it possible to tell (without using `threading.local`) if the current thread is inside a context manager?

**Comment by luk3yx** [comment]
I have created a (WIP) `irc.ensure_connection` in my new [megairc](https://github.com/luk3yx/megairc) repo.

**Comment by impredicative** [comment]
Is the new `megairc` package meant to be used alongside `miniirc` in order to get the desired functionality?

**Comment by luk3yx** [comment]
It is, however it is not on PyPI yet.

**Comment by luk3yx** [comment]
Are you still interested in this being added to miniirc itself (as opposed to being a feature in another package)?

**Comment by impredicative** [comment]
No. For now I think it's okay to have it in miniirc-extras. If I later have a compelling reason for wanting it in miniirc, I may then revisit the topic.
