### ISSUE TITLE
Handler as a method in a class

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#16]
I will come around to the other preexisting issue later, but for now I'm curious about registering a handler which is a method in a class, and not a standalone function.

For example, I can easily start a target method in a thread which automatically gets `self` as its first argument. In a similar manner, I'd like to be able to register a handler which automatically gets `self` as its first argument (assuming I registered it for a method, not a function). Is this possible? This could significantly simplify some code for me. If this description of the issue is not clear, I can share sample code. Thanks.

**Comment by luk3yx** [comment]
You could possibly do `irc.Handler('PRIVMSG')(self.privmsg_func)` inside your `__init__`.

**Comment by impredicative** [comment]
If I do that, will `privmsg_func` then receive `self` as its first argument when it's called, or not?

**Comment by luk3yx** [comment]
It should (as long as you do it in `__init__`).

**Comment by impredicative** [comment]
I used `miniirc.Handler('PRIVMSG')(self.privmsg_func)` in my `__init__`, and this works. It wouldn't hurt to have an example of this in the miniirc readme. Thanks.

**Comment by impredicative** [comment]
@luk3yx Whenever possible, I encourage documenting the above line of code somewhere in the readme. It is not obvious and is expected to be generally useful.

**Comment by luk3yx** [comment]
I have added [some documentation](https://github.com/luk3yx/miniirc#making-existing-functions-handlers), if there's a problem with it please let me know.
