### ISSUE TITLE
Consider adding git tags

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#19]
For each new release to PyPI, please consider adding a git tag corresponding to the associated git commit. For example, the 1.3.2 release would then correspond to the 1.3.2 or v1.3.2 tag. I don't strongly need this, but in general it's not a bad idea.

Feel free to close this issue after reading it.

**Comment by luk3yx** [comment]
I have retroactively added tags for every PyPI version (and some extras that weren't on PyPI), and killed 25 minutes.

**Comment by impredicative** [comment]
Thanks for all the hard work. I want to also share that my RSS bot now has at least one user (FingerlessGlov3s) who is running his own instance of it. This of course means miniirc is used that much more too.
