### ISSUE TITLE
Changelog request

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#21]
Hello. Starting with the most recent release, I think I will find a changelog useful for miniirc. It doesn't necessarily have to be comprehensive and list internal improvements. It just has to minimally list the points that would be relevant to users, e.g. new features and things to watch out for. I assume this can go in a changelog file and/or somehow show up on the Releases page. Thanks.

**Comment by luk3yx** [comment]
I am not sure how I can keep the "Releases" tab in sync on both GitHub and GitLab easily, so I have just created a `CHANGELOG.md`.
