### ISSUE TITLE
Publish to PyPI via GitHub Releases only, using CI CD workflow

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#22]
It is easy to forget to tag a new PyPI release on GitHub. This can be automated, for example by publishing to PyPI via the Releases feature in the web UI of GitHub. This or some other condition would trigger the PyPI publish. In this way your PyPI token can also avoid existing on your local disk where it can risk being stolen. I'm using this approach in my packages [urltitle](https://github.com/impredicative/urltitle/blob/master/.github/workflows/cicd.yml) and [bitlyshortener](https://github.com/impredicative/bitlyshortener/blob/master/.github/workflows/cicd.yml) using GitHub Actions.

**Comment by luk3yx** [comment]
I have added a starter workflow (in commit 767e0bf8c65aa9957e6b2cc415ea9a0ad026b9fd), I will leave this issue open until the next miniirc release to ensure it works correctly.

I also use full disk encryption, my PyPI password *shouldn't* be able to be stolen easy.

**Comment by impredicative** [comment]
In the workflow, I encourage using a PyPI token instead of the username and password. The token can be generated on the PyPI website.

Even with full disk encryption, there are sometimes malicious libraries that read files on disk and upload their contents.

**Comment by luk3yx** [comment]
> In the workflow, I encourage using a PyPI token instead of the username and password. The token can be generated on the PyPI website. I acknowledge that what's there now is a starter workflow.

Thanks for pointing that option out, I have changed GitHub actions to use a token (and enabled 2FA on PyPI).

**Comment by impredicative** [comment]
The Twine username in the workflow can just be `__token__`. It is not a secret anymore. Just the Twine password is a secret.
