### ISSUE TITLE
Underscore keeps getting appended to nick

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#26]
If my bot's nick is say `MyBot`, then over time, its nick keeps getting changed to `MyBot_`, then sometimes `MyBot__`, and rarely even `MyBot___`, etc. I have tried to remedy this without reliable success. Can `miniirc` be updated to prevent this or to reliably fix it when it happens? This is with v1.8.4 and Python 3.11. I think that the responsibility of ensuring that the bot always has the correct nick should be that of `miniirc`.

**Comment by luk3yx** [comment]
Currently `irc.nick` is updated whenever the bot changes nickname. If the bot can't get `MyBot`, it will change to `MyBot_`, and so on. The new nickname is (unfortunately) used if the bot reconnects to IRC.

I think the best fix would be to add a `keepnick=True` argument that makes miniirc store the original nickname and try and obtain the original nickname if it can't while connecting.

**Comment by luk3yx** [comment]
I'm just worried about breaking something since I plan on making `irc.nick` store the original nickname and `irc.current_nick` store the current one when keepnick is enabled, though `irc.current_nick` has existed as an alias since 2019 and any potential breakage would likely be minimal.

**Comment by luk3yx** [comment]
> Something will break if the bot stays unconnected for a long time if it cannot get the correct nick.

Good point. I've released miniirc v1.9.0 with a "keepnick" feature (without an option to disable it), if there are any bugs please reopen this issue or create a new one.

I've made `irc.nick` a property that emulates what it does in earlier versions, hopefully that will prevent anything from breaking.
